/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbdd1718.practica01.interfaces;


import bbdd1718.practica01.clases.AppFutbol;
import bbdd1718.practica01.clases.Arbitro;
import bbdd1718.practica01.clases.Personas;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class AltaArbitro extends javax.swing.JFrame {

    /**
     * Creates new form AltaArbitro
     */
    //Variables
    Arbitro a;
    
    public AltaArbitro() {
        initComponents();
        this.setLocationRelativeTo(null);//centramos.
        this.setTitle("Nuevo arbitro");
        for(int i=0;i<AppFutbol.posicionesArbitro.length;i++){
            this.selectPosicion.addItem(AppFutbol.posicionesArbitro[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        labelTitulo = new javax.swing.JLabel();
        labelSubTitulo = new javax.swing.JLabel();
        textIdArbitro = new javax.swing.JTextField();
        labelIdJugador = new javax.swing.JLabel();
        textName = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelSalario = new javax.swing.JLabel();
        textSalario = new javax.swing.JTextField();
        labelSimbolEuro = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        textTelefono = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        selectPosicion = new javax.swing.JComboBox<>();
        labelPosicion = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        buttonAceptar = new javax.swing.JButton();
        buttonLimpiar = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        warningEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setText("App Futbol Menu");

        labelSubTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSubTitulo.setText("Nuevo arbitro");

        labelIdJugador.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelIdJugador.setText("ID:");

        textName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNameActionPerformed(evt);
            }
        });

        labelName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelName.setText("Nombre:");

        labelSalario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelSalario.setText("Salario:");

        textSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSalarioActionPerformed(evt);
            }
        });

        labelSimbolEuro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSimbolEuro.setText("€");

        labelTelefono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelTelefono.setText("Telefono:");

        labelEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelEmail.setText("E-mail:");

        textEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textEmailFocusLost(evt);
            }
        });

        selectPosicion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        selectPosicion.setName(""); // NOI18N
        selectPosicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPosicionActionPerformed(evt);
            }
        });

        labelPosicion.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelPosicion.setText("Poscion:");

        buttonAceptar.setText("Aceptar");
        buttonAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAceptarMouseClicked(evt);
            }
        });
        buttonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAceptarActionPerformed(evt);
            }
        });

        buttonLimpiar.setText("Limpiar");
        buttonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLimpiarMouseClicked(evt);
            }
        });
        buttonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLimpiarActionPerformed(evt);
            }
        });

        buttonCancel.setText("Menu");
        buttonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCancelMouseClicked(evt);
            }
        });
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        warningEmail.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmail)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buttonAceptar)
                                .addGap(68, 68, 68)
                                .addComponent(buttonLimpiar)
                                .addGap(66, 66, 66)
                                .addComponent(buttonCancel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelIdJugador)
                                    .addComponent(labelTelefono))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labelPosicion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(selectPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addComponent(textIdArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelName)
                                .addGap(27, 27, 27)
                                .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelSimbolEuro, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textEmail)
                                    .addComponent(warningEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(labelTitulo))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(labelSubTitulo)))))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textIdArbitro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdJugador))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSalario)
                    .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSimbolEuro)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelName))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectPosicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPosicion)
                    .addComponent(labelTelefono)
                    .addComponent(textTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(warningEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAceptar)
                    .addComponent(buttonLimpiar)
                    .addComponent(buttonCancel))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNameActionPerformed

    private void textSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSalarioActionPerformed

    private void textEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailFocusLost
        // Comprobamos el email al quitar el cursos de la caja de texto.
        
        if(isEmail()){
            this.warningEmail.setText("");
            this.buttonAceptar.setVisible(true);
        }else{//El email no coincide.
            this.warningEmail.setText("Email erroneo");
            this.buttonAceptar.setVisible(false);

        }
    }//GEN-LAST:event_textEmailFocusLost

    private void selectPosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPosicionActionPerformed

    private void buttonAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAceptarMouseClicked
        // Botón para dar de alta al arbitro.
        
        String[] msg = {"Datos incompletos","ID, telefono, salario o email erroneo","Introduce correctamente el email o salario"};
        int msgIndice=1;
        boolean crearArbitro=true; //ture-> Crea estadio, false-> No crea estadio,        
        //Elementos del jugador
        int idArbitro = 0;
        Double salario = 0.0;
        String telefono = "";
        String nombre = "";
        String email = "";
        String posicion = "";//Equivalente a tipo
        
        //
        if(this.textName.getText().equals("") || this.textEmail.getText().equals("") || 
                this.textIdArbitro.getText().equals("") || this.textSalario.getText().equals("") ||
                this.textTelefono.getText().equals("") ){
            //Algún campo est vacío.
            msgIndice=0;
            crearArbitro=false;
            
        }else{//Los camos estan completos
            
            try{
                idArbitro = Integer.parseInt(this.textIdArbitro.getText());
                salario = Double.parseDouble(this.textSalario.getText());

            }catch(Exception e){//Introdujo un carracter no numérico
                msgIndice=2;
                crearArbitro=false;
                
            }
            
            posicion = AppFutbol.posicionesArbitro[ this.selectPosicion.getSelectedIndex() ];
            email = this.textEmail.getText();
            telefono = this.textTelefono.getText();
            nombre = this.textName.getText();
            
            //Comprobamos la estrucutra del email y el teléfono.
            if(!( isEmail() )|| !( isTele() )){//Si el email no tiene la extructura x@x.x y el telefono +XXxxxxxxxx
                
                msgIndice=2;
                crearArbitro = false;
                
            }else{//Si cumple la estructura
                
                 //Comprobamos que los datos sean correctos
                if(idArbitro<0 || salario<=0){//El identificador debe ser mayor o igual que 0.
                    msgIndice=1;
                    crearArbitro = false;
                }else{
                    
                    if(!AppFutbol.lArbitros.isEmpty()){//Lista no vacía
                        if(AppFutbol.lArbitros.containsKey(idArbitro)){
                            //El id del estadio ya existe en la lista de estadios.
                            int y= JOptionPane.showConfirmDialog(null, "Id del jugador ya en uso, ¿Modificar estadio de la lista? ",
                                "AppFutbol",JOptionPane.YES_NO_OPTION);
                            if(y==JOptionPane.NO_OPTION){//Dijo que no queria borrar el estadio ya existente.
                                crearArbitro=false;
                                msgIndice=-1;
                            }

                        }//Fin del if, para ver si el identificador esta en uso
                    }//Fin del if, para ver si esta la lista vacia.
                }//Fin del if-else de validar la estrucutra e-amil y telefono
            }//Fin del if-else que comprueba si estan vacios o no los inputs de entrada
        } //Fin del if-esle que compureba si el id y el sarlario
        
        if(!crearArbitro){
            if(msgIndice!=-1){//Si el error no procede del id ya en uso.
                JOptionPane.showMessageDialog(null, msg[msgIndice],
                    "AppFutbol",JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            Personas p = new Personas(idArbitro,nombre,email,telefono);
            a = new Arbitro(p,posicion,salario );
            AppFutbol.AltaArbitro(a);

            this.setVisible(false);
            AppFutbol.iu.setVisible(true);
        } 
    }//GEN-LAST:event_buttonAceptarMouseClicked

    private void buttonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAceptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAceptarActionPerformed

    private void buttonLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLimpiarMouseClicked
        // Botón para limpiar cajas de Texto
        this.textName.setText("");
        this.textEmail.setText("");
        this.warningEmail.setText("");
        this.buttonAceptar.setVisible(true);
        this.textIdArbitro.setText("");
        this.textTelefono.setText("");
        this.textSalario.setText("");
        this.selectPosicion.setSelectedIndex(0);

    }//GEN-LAST:event_buttonLimpiarMouseClicked

    private void buttonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLimpiarActionPerformed

    private void buttonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCancelMouseClicked
        // Botón para volver al menú
        this.dispose();
        AppFutbol.iu.setVisible(true);

    }//GEN-LAST:event_buttonCancelMouseClicked

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaArbitro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AltaArbitro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAceptar;
    private javax.swing.JButton buttonCancel;
    private javax.swing.JButton buttonLimpiar;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelIdJugador;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPosicion;
    private javax.swing.JLabel labelSalario;
    private javax.swing.JLabel labelSimbolEuro;
    private javax.swing.JLabel labelSubTitulo;
    private javax.swing.JLabel labelTelefono;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JComboBox<String> selectPosicion;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textIdArbitro;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textSalario;
    private javax.swing.JTextField textTelefono;
    private javax.swing.JLabel warningEmail;
    // End of variables declaration//GEN-END:variables
    //Metodo para validar el correo electronico
    public boolean isEmail(){
        String o = "^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$";
       
        if(Pattern.matches(o,this.textEmail.getText())){
            return true;
        }else{
            return false;
        }
    }
    //Metodo para validar el telefono
    public boolean isTele(){
        String o = "^\\+\\d{1,3}?[- .]?\\(?(?:\\d{2,3})\\)?[- .]?\\d\\d\\d[- .]?\\d\\d\\d\\d$";
        //Si queremos que el + sea opciona: "^\\+?\\d{1,3}?[- .]?\\(?(?:\\d{2,3})\\)?[- .]?\\d\\d\\d[- .]?\\d\\d\\d\\d$"
        if(Pattern.matches(o,this.textTelefono.getText())){
            return true;
        }else{
            return false;
        }
    }
}
