/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbdd1718.practica01.interfaces;

import bbdd1718.practica01.clases.AppFutbol;
import bbdd1718.practica01.clases.Jugador;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class MostrarJugadoresDadaPosicion extends javax.swing.JFrame {

    /**
     * Creates new form MostrarJugadoresDadaPosicion
     */
    public MostrarJugadoresDadaPosicion() {
        initComponents();
        this.setLocationRelativeTo(null);//centramos.
        this.setTitle("Posiciones de los Jugadores");
        
        //Lista de estadios
        this.jComboBoxPosiciones.addItem("Seleccione posicion");
        for(int i=0; i<AppFutbol.posicionesJugador.length;i++){
            this.jComboBoxPosiciones.addItem(AppFutbol.posicionesJugador[i]);//Lo añaddimos al jList de Arbitros
        }
        this.jComboBoxPosiciones.setToolTipText("Posicion a buscar");
        this.jComboBoxPosiciones.setSelectedIndex(0); //Valor por defcto
        vaciarResultado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        labelSubTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxPosiciones = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListResultadoBusqueda = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setText("App Futbol Menu");

        labelSubTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSubTitulo.setText("Posiciones de los Jugadores");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Posiciones:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Resultado:");

        jListResultadoBusqueda.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListResultadoBusqueda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jListResultadoBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResultadoBusquedaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListResultadoBusqueda);

        jButton1.setText("Menu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2)
                            .addGap(111, 111, 111)
                            .addComponent(jButton3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxPosiciones, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelSubTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxPosiciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Boton para volver al menu
        this.dispose();
        AppFutbol.iu.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // Boton para limpiar
        this.jComboBoxPosiciones.setSelectedIndex(0); //Valor por defcto
        vaciarResultado();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // Boton para buscar
        Boolean exito = false;
        
        if(this.jComboBoxPosiciones.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Selecionado una posicion ",
                        "AppFutbol",JOptionPane.ERROR_MESSAGE);
        }else{
            String posicionBusqueda = ((String) this.jComboBoxPosiciones.getSelectedItem()); //Valor del jlistEstadios

            DefaultListModel modelo = new DefaultListModel(); //Contendor
            for(Jugador jugadorBuscar : AppFutbol.lJugadores.values()){
                if(jugadorBuscar.getPosicion().equals(posicionBusqueda)){
                    modelo.addElement(jugadorBuscar.id+": "+jugadorBuscar.nombre);
                    exito=true;
                }
            }
            
            if(exito){
                this.jListResultadoBusqueda.setEnabled(true);
                this.jListResultadoBusqueda.setModel(modelo); //Lo añaddimos al jList
                this.jListResultadoBusqueda.setToolTipText("ID: Nombre");
            }else{
                JOptionPane.showMessageDialog(null, "No hay jugadores con la posicon: "+posicionBusqueda,
                        "AppFutbol",JOptionPane.ERROR_MESSAGE);
                this.jListResultadoBusqueda.setEnabled(false);
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jListResultadoBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResultadoBusquedaMouseClicked
        // Mostrar la ficha del jugador seleccionado
        if(this.jListResultadoBusqueda.getSelectedValue()=="" || this.jListResultadoBusqueda.getSelectedValue()==null){ //Hizo clic en la lista vacia
            JOptionPane.showMessageDialog(null, "Error, no se detecta el partido seleccionado ",
                        "AppFutbol",JOptionPane.ERROR_MESSAGE);
        }else{//Presiono sobre partido
            //Extremos el identificador del jugador
            String [] datos = this.jListResultadoBusqueda.getSelectedValue().split(":");
            short keyIntJugador = Short.parseShort(datos[0]);
            //Mostramos la ficha del jugador
            AppFutbol.datosSistema[0]=1; //Indiamos que no nos informe si el jugador pertenece a un equipo (solicitud de jugadores disponibles)
            AppFutbol.datosSistema[1] = keyIntJugador; //Indicamos la posicion del jugador
            new MostrarJugador();            
        }
    }//GEN-LAST:event_jListResultadoBusquedaMouseClicked

    /**
     *  Método para eliminar el contenido de la jList
     */
    public void vaciarResultado(){
        DefaultListModel modeloVacio = new DefaultListModel(); //Contendor
        modeloVacio.addElement("");
        this.jListResultadoBusqueda.setEnabled(false);
        this.jListResultadoBusqueda.setModel(modeloVacio); //Lo añaddimos al jList
        this.jListResultadoBusqueda.setToolTipText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarJugadoresDadaPosicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarJugadoresDadaPosicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarJugadoresDadaPosicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarJugadoresDadaPosicion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarJugadoresDadaPosicion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBoxPosiciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListResultadoBusqueda;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelSubTitulo;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
