/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bbdd1718.practica01.interfaces;

import bbdd1718.practica01.clases.AppFutbol;
import bbdd1718.practica01.clases.Equipo;
import bbdd1718.practica01.clases.Partido;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Andres
 */
public class MostrarPartidosDeEquipo extends javax.swing.JFrame {

    /**
     * Creates new form MostrarPartidosDeEquipo
     */
    public MostrarPartidosDeEquipo() {
        initComponents();
        this.setLocationRelativeTo(null);//centramos.
        this.setTitle("Partidos de un Equipo");
        
        //Lista de estadios
        this.jComBoxEquipos.addItem("Seleccione Equipo");
        for(Equipo equi : AppFutbol.lEquipos.values()){
            this.jComBoxEquipos.addItem(equi.getIdEquipo()+": " + equi.getNameEquipo());//Lo añaddimos al jList de Arbitros
        }
        this.jComBoxEquipos.setToolTipText("Id - Nombre");
        this.jComBoxEquipos.setSelectedIndex(0); //Valor por defcto
        vaciarResultado();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelSubTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComBoxEquipos = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListResutadoPartidos = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelTitulo.setText("App Futbol Menu");

        labelSubTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSubTitulo.setText("Datos del Partido");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Equipos:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Resultado:");

        jListResutadoPartidos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListResutadoPartidos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListResutadoPartidosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListResutadoPartidos);

        jButton1.setText("Menu");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Limpiar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Buscar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelTitulo)
                                        .addGap(126, 126, 126))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(labelSubTitulo)
                                        .addGap(146, 146, 146))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(105, 105, 105)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComBoxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComBoxEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // Botón para volver al menu
        this.dispose();
        AppFutbol.iu.setVisible(true);
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // Botón para limpiar
        this.jComBoxEquipos.setSelectedIndex(0); //Valor por defcto
        vaciarResultado();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // Botón par buscar los partidos de un equipo
        Boolean exito = false;
        
        if(this.jComBoxEquipos.getSelectedIndex()==0){
            JOptionPane.showMessageDialog(null, "Selecionado un equipo ",
                        "AppFutbol",JOptionPane.ERROR_MESSAGE);
        }else{
            
            String [] keyStringEstadio = ((String) this.jComBoxEquipos.getSelectedItem()).split(":"); //Valor del jlistEstadios
            String nameEqBuscar = keyStringEstadio[1].replaceAll("\\s",""); //Extraemos el nombre del equipo, eliminado: espacios, tabuladores, retornos
            
            DefaultListModel modelo = new DefaultListModel(); //Contendor
            for(Partido var : AppFutbol.lPartidos.values()){
                /*
                System.out.println("Equipo 1: "+var.getEq1().getNameEquipo());
                System.out.println("Equipo 2: "+var.getEq2().getNameEquipo());
                System.out.println("Equipo de busqueda: "+nameEqBuscar);
                System.out.println("Caso A: "+var.getEq1().getNameEquipo().equals(nameEqBuscar) );
                System.out.println("Caso B: "+var.getEq2().getNameEquipo().equals(nameEqBuscar) );
                System.out.println("-------------------------------------------");
                */
                if(var.getEq1().getNameEquipo().equals(nameEqBuscar) || var.getEq2().getNameEquipo().equals(nameEqBuscar)){
                    modelo.addElement(var.getIdPartido()+": "+var.getFecha()+", "+var.getEq1().getNameEquipo()+" vs "+var.getEq2().getNameEquipo()+", "+var.getIda());
                    exito = true;
                }
            }
            
            if(exito){
                this.jListResutadoPartidos.setEnabled(true);
                this.jListResutadoPartidos.setModel(modelo); //Lo añaddimos al jList
                this.jListResutadoPartidos.setToolTipText("ID: Fecha, Equipo 1 vs Equipos 2, ida");
            }else{
                JOptionPane.showMessageDialog(null, "No hay partidos para el equipo "+nameEqBuscar,
                        "AppFutbol",JOptionPane.ERROR_MESSAGE);
                this.jListResutadoPartidos.setEnabled(false);
            }
            
            

        }
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jListResutadoPartidosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListResutadoPartidosMouseClicked
        // Click sobre el partido de la lista
        if(this.jListResutadoPartidos.getSelectedValue()==""|| this.jListResutadoPartidos.getSelectedValue()==null){ //Hizo clic en la lista vacia
            JOptionPane.showMessageDialog(null, "Error, no se detecta el partido seleccionado ",
                        "AppFutbol",JOptionPane.ERROR_MESSAGE);
        }else{//Presiono sobre partido
            String [] datos = this.jListResutadoPartidos.getSelectedValue().split(":");
            short keyIntPartido = Short.parseShort(datos[0]);
            AppFutbol.datosSistema[1] = keyIntPartido;
            new MostrarPartido();
            
        }
        
    }//GEN-LAST:event_jListResutadoPartidosMouseClicked
    /**
     *  Método para eliminar el contenido de la jList
     */
    public void vaciarResultado(){
        DefaultListModel modeloVacio = new DefaultListModel(); //Contendor
        modeloVacio.addElement("");
        this.jListResutadoPartidos.setEnabled(false);
        this.jListResutadoPartidos.setModel(modeloVacio); //Lo añaddimos al jList
        this.jListResutadoPartidos.setToolTipText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MostrarPartidosDeEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MostrarPartidosDeEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MostrarPartidosDeEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MostrarPartidosDeEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MostrarPartidosDeEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComBoxEquipos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jListResutadoPartidos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelSubTitulo;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
